### PR TITLE
Feature/project configuration

### PR DESCRIPTION
**Pull request by rc-softdev-admin**
CMake configuration for GTest and Eigen3 done with GreatCMakeCookOff now. A few issues including directories came up, but seem all sorted now.

### CODE REVIEW

**Comment by raquel-ucl** [comment]
ok to test

**Comment by jenshnielsen** [comment]
ok to test

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by jenshnielsen** [comment]
Looks like cmake on Legion gets confused by `cmake_policy(VERSION 3.0)` 

```
CMake Error at CMakeLists.txt:26 (cmake_policy):
  An attempt was made to set the policy version of CMake to "3.0" which is
  greater than this version of CMake.  This is not allowed because the
  greater version may have new policies not known to this CMake.  You may
  need a newer CMake version to build this project.
```

Which is odd since cmake on legion is 3.2.1

The intel job fails due to a missing swig. We need to add a module for that.

I fixed gcc on the Mac issue

**Comment by jenshnielsen** [comment]
Otherwise this looks like a good beginning. I think we should see if we can use the find python/numpy  and c++ feature tests from cookoff to. But that can be done in a separate pr

**Comment by jenshnielsen** [comment]
We should also make sure to add organisation rather than individual users to the list of verified admins

**Comment by jenshnielsen** [comment]
At least we should delete the findeigen file

**Comment by raquel-ucl** [comment]
retest this please

**Comment by jenshnielsen** [comment]
retest this please

**Comment by raquel-ucl** [comment]
retest this please

**Comment by raquel-ucl** [comment]
retest this please

**Comment by raquel-ucl** [comment]
retest this please

**Comment by raquel-ucl** [comment]
retest this please

**Pull request merged**
